#!/usr/bin/env python3
"""Bake the demo audio into flash as a C header the ESP32 plays standalone.

Two jobs beyond format conversion, both aimed at a small 16 ohm driver:

  LOUDNESS. A 0.25 W driver on an 8 ohm bridge is quiet, and most of what it
  is given is wasted. We high-pass at 150 Hz (the cone cannot move that air,
  so bass only steals headroom), then apply soft-knee compression so the RMS
  rises without the peaks clipping. Perceived loudness is set by RMS, not by
  peak, so this is worth far more than raising the peak amplitude.

  SIZE. 8 s of 16 kHz 16-bit is 256 KB per clip. mu-law companding halves that
  at no audible cost for speech, which is what mu-law was designed for.

    python3 make_audio_header.py
"""
import numpy as np, subprocess, os, sys
from scipy.signal import butter, sosfilt

HERE = os.path.dirname(os.path.abspath(__file__))
SRC  = os.path.join(HERE, "..", "..", "E03", "runs", "nearfield", "zero")
FS   = 16000
CLIPS = [("BEFORE", "1_BEFORE.mp3"), ("AFTER", "4_AFTER_plus_NEARFIELD_gate.mp3")]

def load(path):
    raw = subprocess.run(
        ["ffmpeg", "-v", "error", "-i", path, "-ac", "1", "-ar", str(FS),
         "-f", "s16le", "-"], capture_output=True, check=True).stdout
    return np.frombuffer(raw, "<i2").astype(np.float64) / 32768.0

def limiter(y, thr=0.95, atk=8, rel=1200):
    """Gain reduction on PEAKS only. Never raises anything, so the noise
    floor is untouched -- which is the entire difference from what this
    replaced."""
    env = np.abs(y)
    g = np.ones_like(y)
    cur = 1.0
    for i in range(len(y)):
        want = min(1.0, thr / (env[i] + 1e-9))
        if want < cur: cur += (want - cur) / atk      # fast attack
        else:          cur += (want - cur) / rel      # slow release
        g[i] = cur
    return y * g

def loudify(x):
    """High-pass, then level by SPEECH, then limit peaks. No upward
    compression of any kind.

    The previous version raised quiet passages with 1/env**0.65, which lifted
    the background 12.6 dB and collapsed the speech-to-background gap from
    14.0 dB to 8.8 dB. On a small speaker that is heard as a constant buzz
    with the voice buried in it. Loudness has to come from removing headroom
    above the peaks, never from raising the floor.
    """
    x = sosfilt(butter(2, 150.0, "hp", fs=FS, output="sos"), x)  # cone can't do bass
    x /= (np.abs(x).max() + 1e-9)
    return x

def match_speech(y, target_dbfs=-15.0):
    """Level by SPEECH, not by overall RMS.

    The gated clip has real silence between words, so its overall RMS is
    several dB lower than the ungated one. Matching overall RMS would make
    the BETTER version play quieter and read as worse in an A/B. Matching the
    loud frames instead makes the voice equally loud in both, so the only
    audible difference is the background -- which is the whole point.
    """
    n = 320
    m = len(y) // n
    e = (y[:m*n].reshape(m, n) ** 2).mean(1)
    loud = e >= np.quantile(e, 0.70)
    rms = np.sqrt(e[loud].mean() + 1e-20)
    y = y * (10 ** (target_dbfs / 20) / rms)
    if np.abs(y).max() > 0.95:
        y = limiter(y)
    return np.clip(y, -0.99, 0.99)

def mulaw(x):
    MU = 255.0
    s = np.sign(x)
    m = np.log1p(MU * np.abs(x)) / np.log1p(MU)
    return np.clip(np.round((s * m * 127.0) + 128), 0, 255).astype(np.uint8)

out = ["/* GENERATED by make_audio_header.py -- do not edit by hand. */",
       "#pragma once", "#include <pgmspace.h>", "#include <stdint.h>", ""]
for name, fn in CLIPS:
    p = os.path.join(SRC, fn)
    if not os.path.exists(p):
        sys.exit(f"missing {p}")
    x = match_speech(loudify(load(p)))
    u = mulaw(x)
    n = 320; m = len(x)//n
    e = (x[:m*n].reshape(m, n) ** 2).mean(1)
    sp = 10*np.log10(e[e >= np.quantile(e, 0.70)].mean() + 1e-20)
    qt = 10*np.log10(e[e <= np.quantile(e, 0.25)].mean() + 1e-20)
    print(f"{name:8} {len(u)/FS:5.2f} s  {len(u)/1024:6.1f} KB  "
          f"speech {sp:+.1f} dBFS  background {qt:+.1f} dBFS")
    out.append(f"#define {name}_LEN {len(u)}")
    out.append(f"const uint8_t {name}_ULAW[] PROGMEM = {{")
    for i in range(0, len(u), 24):
        out.append("  " + ",".join(str(v) for v in u[i:i+24]) + ",")
    out.append("};\n")

# mu-law expansion table, so the ESP32 decodes with one array lookup
tbl = []
for b in range(256):
    y = (b - 128) / 127.0
    s = 1.0 if y >= 0 else -1.0
    v = s * (np.expm1(abs(y) * np.log1p(255.0)) / 255.0)
    tbl.append(int(np.clip(round(v * 32000), -32768, 32767)))
out.append("const int16_t ULAW_TBL[256] PROGMEM = {")
for i in range(0, 256, 16):
    out.append("  " + ",".join(str(v) for v in tbl[i:i+16]) + ",")
out.append("};")

open(os.path.join(HERE, "demo_audio.h"), "w").write("\n".join(out) + "\n")
print("wrote demo_audio.h",
      f"{os.path.getsize(os.path.join(HERE,'demo_audio.h'))/1024:.0f} KB source")
